### PR TITLE
Fix sera spamming T2 sonars

### PR DESCRIPTION
**Pull request by speed2CZ**
Since sera sonars are now mobile, they can't be part of the base structures anymore, but built seperatly.

### CODE REVIEW

**Comment by Garanas** [comment]
What happened in the _save files?

**Comment by speed2CZ** [comment]
I moved the sonars out of the bases,

**Comment by Garanas** [comment]
Check - feel free to merge these as you see fit. I don't have the experience with OpAI to confirm your changes.

**Comment by speed2CZ** [comment]
The same system is already used for T3 sonars, since they are also mobile.

**Pull request merged**
