### PR TITLE
Fixes for the new mobile factories

### PR DESCRIPTION
**Pull request by speed2CZ**
Should be all working now

### CODE REVIEW

**Comment by Garanas** [comment]
You can turn it into a mergeable-pr when it is no longer a WIP

**Comment by speed2CZ** [comment]
@Garanas There is some rouge rally point happening, it seems to be placed to the spot where the unit got created.
The roll off point is correct, and its given as a second order, thats where my cursor is.

ForgedAlliance_2023-08-24_17-23-13

The closest rally point is above the tempest, so I think it's grabbing the position where the unit got created
SCEditor_2023-08-24_18-24-11

Can you look into it? I have no idea where it's coming from. The mission script is not setting any rally point.

**Comment by Garanas** [comment]
I'll look into it

**Comment by Garanas** [comment]
Fixed with: https://github.com/FAForever/fa/pull/5357

**Comment by Garanas** [comment]
@speed2CZ can you look into the conflict?

**Comment by speed2CZ** [comment]
Its resolved, but not tested. Someone should check if the fatboys and atlantises in Kael are producing units.

**Comment by Garanas** [comment]
By merging https://github.com/FAForever/faf-coop-maps/pull/424 we have a new conflict, @Dhomie would you have time to review it here too?

**Comment by Dhomie** [comment]
Lemme take a look.

**Comment by Dhomie** [comment]
Ok, the conflict was related to certain functions that were updated, relocated, or removed/merged.
It should be resolved now, I also removed a completely commented-out objective that I forgot to do so before.

I'll link the relevant lines that were changed for the remaster for reference just in case, these are the ones that this PR were in conflict with:

- The mobile factories thread has been changed and moved along with some VO functions: https://github.com/FAForever/faf-coop-maps/blob/4e04f941a7b015422a67e53f84ae7db7f78770d2/SCCA_Coop_R06/SCCA_Coop_R06_script.lua#L907

- The taunt functions have been moved to the bottom of the script file: https://github.com/FAForever/faf-coop-maps/blob/4e04f941a7b015422a67e53f84ae7db7f78770d2/SCCA_Coop_R06/SCCA_Coop_R06_script.lua#L1235

- The `M2AeonAirAttack()` function, which spawned a few air units from off-map to attack the Control Center, was removed, because the Aeon now mostly picks targets for its air units based on threat.

**Pull request merged**
