### PR TITLE
Rework Cybran M6

### PR DESCRIPTION
**Pull request by speed2CZ**
- Fixed missing Mass markers in the UEF main base
- Fixed UEF and Aeon structures overlapping
- Enabled weather effects
- UEF now has T3 naval factories in the main base instead of T2
- Added Omni into UEF main base
- Added T3 sonars into Aeon and UEF base
- Fixed UEF stalling energy
- More experimental attacks
- SMD in Aeon base

### CODE REVIEW

**Comment by Dhomie** [comment]
@Garanas Regarding #424, this PR (#379) will either have to be closed/reverted, or #424 will have to be reverted.
Speed's rework and mine are not compatible with one another (hence the conflicts), it's up to you guys which rework you'd prefer.

**Comment by Garanas** [comment]
That's up to the campaign team. I'm fine with either, as long as it is an improvement 😃

**Comment by Dhomie** [comment]
@speed2CZ What are your thoughts?
#424 has already been merged, and if you're fine with that iteration, this PR could be closed.

**Comment by speed2CZ** [comment]
Im fine with your version

**Pull request closed without merging**
