### PR TITLE
Remove walls from starting base

### PR DESCRIPTION
**Pull request by aeoncleanse**
They are incredibly irritating and just suck up APM reclaiming them anyway

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Re-designed this so that instead of being flat out removed, they begin as wrecks.

**Comment by Sheeo** [comment]
Did you do so in another PR?

**Comment by aeoncleanse** [comment]
Not sure what you mean... I just reverted, rebased, then push -f to branch with the new setup because the PR had not been approved.

**Comment by Sheeo** [comment]
I see, I got confused because the diff looked identical at the first glance. Looks good :+1:

**Pull request merged**
