### PR TITLE
Spawn things with the right player

### PR DESCRIPTION
**Pull request by aeoncleanse**
Mean we don't have to go through the stupidity of transferring everything, and makes the script a bit easier to follow. They only did this because of the way GPG generated the missions using a tool we no longer have.

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Not sure if I should squash the cleanup commits into one, or leave as they are all nonfunctional?

**Comment by ChrisKitching** [comment]
Squash.

**Comment by aeoncleanse** [comment]
Yup, will do

**Comment by aeoncleanse** [comment]
Squished

**Comment by speed2CZ** [comment]
@aeoncleanse why are you fixing something that doesn't need to be fixed at all?

**Comment by aeoncleanse** [comment]
Because it makes the code considerably less insane to understand for the future

**Comment by speed2CZ** [comment]
Also removes good example how to give whole base with all units... This change is not improving anything, if you want to improve missions, you should focus on things that needs to be adjusted and not on things that works perfectly. I dont like these changes

**Comment by aeoncleanse** [comment]
One shouldn't leave annoying, hard to read code which is in the way and unnecessary just to leave an example of how to do something really obvious. Especially seeing as there are plenty of other places in the maps where units are given from one army to another. This just simplifies the start of the mission hugely from a readability standpoint, and will make it easier to modify in the future.

Unless you have some code which depends on this remaining as-is, I really can't fthom your objection. You already know what you need to for your map. The ONLY reason the maps are even like this in the first place is because the map editor GPG used wasn't built to support spawning players with pre-owned buildings.

**Comment by ChrisKitching** [comment]
This does seem to be quite a lot of churn for no real gain (and have a net +ve line count).
Are there any real bugs associated with the old behaviour? Doesn't this affect score semantics a little (players now get points for shit that the base kills during the first cinematic, for example.)

**Comment by aeoncleanse** [comment]
Bugs, no, I just find it a right bloody pain to navigate and keep track of what's going on. No clue as to score semantics, but as it will be the same every time it doesn't matter.

**Pull request closed without merging**
