### PR TITLE
Fixing typo FA M4

### PR DESCRIPTION
**Pull request by speed2CZ**
Maybe simple test if the missions starts would be worth the time to prevent this. Or PR where others could notice :P

### CODE REVIEW

**Comment by Ikoter** [comment]
What the hell am i supposed to do here...

**Comment by ChrisKitching** [comment]
> Maybe simple test if the missions starts would be worth the time to prevent this. Or PR where others could notice :P

This topic has been discussed to exhaustion in Slack.

Kindly refrain from such inflammatory remarks: it's generally wise not to make the person reviewing your code want to strangle you.

**Comment by speed2CZ** [comment]
it was just a suggestion to improve quality of our work to make all the coop players more happy <3

**Comment by Ikoter** [comment]
Its generally wise not to provide such links to someone who has absolutely no knowledge of them. And to address your strangling, read the sentence before this one.

**Comment by speed2CZ** [comment]
If you're the one who posted it on forum. I provided the link so others know its fixed and they don't need to look at it anymore.

**Pull request merged**
