### PR TITLE
Remaster UEF M6

### PR DESCRIPTION
**Pull request by Dhomie**
Initial upload of a remastered version of UEF M6: Operation Stone Wall.

Just like with Cybran M6, it's an overhaul that by default doesn't deviate too much from the original.
However this iteration features some lobby options that can spice things up, like a full map expansion at the end of the mission (hostile AIs only get their full base sizes if the corresponding lobby option is enabled, so no unnecessary structures outside the playable area).

The default options layout is how the original GPG version of the map would play out, just with obvious enhancements.

The mission is available in the coop Discord for testing: https://discord.com/channels/944679492293636116/944681147458273390/1220754088220954634

### CODE REVIEW

**Comment by Garanas** [comment]
@Dhomie do you want this to be part of the release this weekend?

**Comment by Dhomie** [comment]
So far I got no words on any glaring bugs or issues, so sure, it can be part of the release.

**Comment by othbert** [comment]
I don't know if it's specific to the remaster, but my ACU died in the final assault around 65% I think (might have been after the 80% marker), the mission continued as expected. Then black sun was destroyed and Arnold along with aeon and cybran units were walking all over the destroyed site, camera stuck in cinematic view, with no functional keys or the mission failed dialogue appearing, for about 10 minutes before I gave up and killed FAF through the task manager.

**Comment by Dhomie** [comment]
The current mission on the client hasn't been updated yet, it downloads v21 for me, which is the old non-reworked one.

If you got the remastered version from the coop Discord then:

- If you got game logs, I'd appreciate them, would help me to see where things have gone wrong.

- The first issue 'would be intended' if there were 2+ players. This was even in the previous non-reworked versions, if at least 1 player was alive, the mission would continue. Something has gone wrong though if it was just SP.
- As for the objective failure, definitely an issue.

**Comment by othbert** [comment]
Ahh ok, thanks! I am not positive as it was a week or two ago, but I think I git cloned the master branch here... also possible that I just grabbed the last release though. At work at the moment but can check later.

I'm very new to FAF, if you have any pointers on where to grab the logs I'll see about getting them later too.
Yup when I read through and tried to piece together the workflow, I saw the first 'issue' being the actual intended behaviour, at least for coop, I'm running with the faf offline and loading the init_coop lua flag if that makes any difference.

**Comment by Dhomie** [comment]
The FAF client will point you to it: 
Screenshot_17

As for the map, the remastered version has been renamed, see the screenshot below for reference: 
Screenshot_15

**Comment by othbert** [comment]
Thanks! I checked the logs folder but there's nothing from all of last week it seems :S wonder if it's because I had to force kill it? Then again, the latest game_x.log in there is from e03 and I was playing through the missions in order, so nothing showing up, also not of my last play sessions yesterday playing through the Aeon campaign.

As for the map name, yup that's what shows up it my available maps. Also, viewing the _script.lua file I see the same changes that were merged in this PR for example, so it looks like I grabbed the master branch and not an older release.

Also, I forgot to say, but thanks for this remaster by the way, adds a great challenge!

**Comment by Dhomie** [comment]
Both cases non-working mission failures should be fixed with #433.

**Pull request merged**
